Repository YunoHost/yunohost, pull requests merged in 2018-12, with the labels that each got.

#548 Do not use a separate ini file for php pools
  data/helpers.d/backend
Labels: helper, small decision

#542 [enh] Improve upnp support
  src/yunohost/firewall.py
Labels: opinion needed, small decision

#590 [enh] Clean + harden sshd config using Mozilla recommendation
  data/hooks/conf_regen/03-ssh
  data/templates/ssh/sshd_config
Labels: opinion needed, small decision

#594 [fix] Manual migration and disclaimer behaviors
  locales/en.json
  src/yunohost/tools.py
Labels: important, opinion needed, small decision

#518 [fix] Standardize sshd config
  bin/yunoprompt
  data/helpers.d/utils
  data/hooks/conf_regen/03-ssh
  data/templates/ssh/sshd_config
  locales/en.json
  src/yunohost/data_migrations/0007_ssh_conf_managed_by_yunohost_step1.py
  src/yunohost/data_migrations/0008_ssh_conf_managed_by_yunohost_step2.py
  src/yunohost/service.py
  src/yunohost/settings.py
  src/yunohost/tools.py
Labels: important, opinion needed, ready to merge, small decision, test needed

#597 Change message about conf now being managed by service -> yunohost
  locales/en.json
  src/yunohost/service.py
Labels: micro decision, opinion needed

#552 [enh] Human readable date
  src/yunohost/app.py
  src/yunohost/backup.py
  src/yunohost/certificate.py
  src/yunohost/log.py
  src/yunohost/service.py
  src/yunohost/settings.py
Labels: opinion needed, ready to merge, small decision

#595 [fix] Repair tests
  .gitignore
  locales/en.json
  src/yunohost/settings.py
  src/yunohost/tests/test_backuprestore.py
  src/yunohost/tests/test_changeurl.py
Labels: opinion needed, small decision

#574 [enh] Simplify error management
  src/yunohost/app.py
  src/yunohost/backup.py
  src/yunohost/certificate.py
  src/yunohost/data_migrations/0002_migrate_to_tsig_sha256.py
  src/yunohost/data_migrations/0003_migrate_to_stretch.py
  src/yunohost/data_migrations/0005_postgresql_9p4_to_9p6.py
  src/yunohost/data_migrations/0006_sync_admin_and_root_passwords.py
  src/yunohost/data_migrations/0007_ssh_conf_managed_by_yunohost_step1.py
  src/yunohost/data_migrations/0008_ssh_conf_managed_by_yunohost_step2.py
  src/yunohost/domain.py
  src/yunohost/dyndns.py
  src/yunohost/firewall.py
  src/yunohost/hook.py
  src/yunohost/log.py
  src/yunohost/monitor.py
  src/yunohost/service.py
  src/yunohost/settings.py
  src/yunohost/ssh.py
  src/yunohost/tests/test_appslist.py
  src/yunohost/tests/test_appurl.py
  src/yunohost/tests/test_backuprestore.py
  src/yunohost/tests/test_changeurl.py
  src/yunohost/tests/test_settings.py
  src/yunohost/tools.py
  src/yunohost/user.py
  src/yunohost/utils/error.py
  src/yunohost/utils/password.py
  src/yunohost/utils/yunopaste.py
Labels: depends on other PR, medium decision, opinion needed, ready to merge

#600 Autopep8
  src/yunohost/app.py
  src/yunohost/backup.py
  src/yunohost/certificate.py
  src/yunohost/data_migrations/0001_change_cert_group_to_sslcert.py
  src/yunohost/data_migrations/0002_migrate_to_tsig_sha256.py
  src/yunohost/data_migrations/0003_migrate_to_stretch.py
  src/yunohost/data_migrations/0004_php5_to_php7_pools.py
  src/yunohost/data_migrations/0005_postgresql_9p4_to_9p6.py
  src/yunohost/data_migrations/0006_sync_admin_and_root_passwords.py
  src/yunohost/data_migrations/0007_ssh_conf_managed_by_yunohost_step1.py
  src/yunohost/data_migrations/0008_ssh_conf_managed_by_yunohost_step2.py
  src/yunohost/domain.py
  src/yunohost/dyndns.py
  src/yunohost/firewall.py
  src/yunohost/hook.py
  src/yunohost/log.py
  src/yunohost/monitor.py
  src/yunohost/service.py
  src/yunohost/settings.py
  src/yunohost/ssh.py
  src/yunohost/tests/conftest.py
  src/yunohost/tests/test_appslist.py
  src/yunohost/tests/test_appurl.py
  src/yunohost/tests/test_backuprestore.py
  src/yunohost/tests/test_changeurl.py
  src/yunohost/tests/test_settings.py
  src/yunohost/tools.py
  src/yunohost/user.py
  src/yunohost/utils/error.py
  src/yunohost/utils/filesystem.py
  src/yunohost/utils/network.py
  src/yunohost/utils/packages.py
  src/yunohost/utils/password.py
  src/yunohost/utils/yunopaste.py
Labels: opinion needed, small decision

#598 [enh] Ask confirmation before installing low-quality, experimental or third party apps
  data/actionsmap/yunohost.yml
  locales/en.json
  src/yunohost/app.py
Labels: opinion needed, ready to merge, small decision

#602 Also remove /var/mail/<username> directory on user delete (with --purge option)
  data/actionsmap/yunohost.yml
  src/yunohost/user.py
Labels: opinion needed, small decision

#603 [fix] DEBUG-level messages not appearing in actions performed via the API
  bin/yunohost-api
Labels: micro decision, opinion needed
