Repository YunoHost/yunohost, pull requests merged in 2018-05, with the labels that each got.

#445 Move ssh commands into a subcategory of 'user' + fix a few bugs
  data/actionsmap/yunohost.yml
  src/yunohost/ssh.py
  src/yunohost/user.py
Labels: opinion needed, small decision

#429 [enh] Manual migrations
  data/actionsmap/yunohost.yml
  debian/postinst
  locales/en.json
  src/yunohost/dyndns.py
  src/yunohost/tools.py
Labels: important, opinion needed, small decision

#433 [enh] [wip] Stretch migration
  locales/en.json
  src/yunohost/app.py
  src/yunohost/data_migrations/0003_migrate_to_stretch.py
  src/yunohost/service.py
  src/yunohost/tools.py
  src/yunohost/utils/filesystem.py
Labels: depends on other PR, medium decision, opinion needed

#454 [enh] ECDH Curves
  data/templates/nginx/plain/yunohost_admin.conf
  data/templates/nginx/server.tpl.conf
Labels: opinion needed, small decision

#459 [fix] Nginx Regression typo
  data/templates/nginx/server.tpl.conf
Labels: important

#464 Update spectre meltdown checker
  src/yunohost/tools.py
  src/yunohost/vendor/spectre-meltdown-checker/README.md
  src/yunohost/vendor/spectre-meltdown-checker/spectre-meltdown-checker.sh
Labels: opinion needed, small decision

#472 bunch of cleaning in services.py
  src/yunohost/service.py
Labels: micro decision, ready to merge

#460 [enh] Add SOURCE_EXTRACT (true/false) in ynh_setup_source
  data/helpers.d/utils
Labels: helper, ready to merge, small decision

#431 [enh] Allow to disable the backup during the upgrade
  data/helpers.d/utils
Labels: helper, opinion needed, ready to merge, small decision

#471 [fix] Untrusted TLS connection established to
  data/templates/postfix/main.cf
Labels: ready to merge, small decision

#462 [enh] Improve ynh_add_nginx_config
  data/helpers.d/backend
Labels: helper, opinion needed, small decision

#439 [fix] Remove warning from equivs
  data/helpers.d/package
Labels: helper, opinion needed, small decision

#475 [enh] We need a fucking log
  data/helpers.d/package
Labels: helper, important

#469 move service_status to sytemd via dbus
  data/hooks/conf_regen/01-yunohost
  data/templates/yunohost/services.yml
  debian/control
  src/yunohost/service.py
Labels: opinion needed, ready to merge, small decision

#478 We need to set status:null for yunohost pseudo-service
  data/templates/yunohost/services.yml
Labels: micro decision, opinion needed

#238 [enh] Add postgresql helpers
  data/helpers.d/psql
Labels: helper, opinion needed, small decision

#363 [enh] Bootprompt is back
  bin/yunoprompt
  data/other/yunoprompt.service
  debian/install
  debian/postinst
Labels: ready to merge, small decision
