Repository YunoHost/yunohost, pull requests merged in 2018-09, with the labels that each got.

#522 Run hook_exec as root by default
  src/yunohost/app.py
  src/yunohost/backup.py
  src/yunohost/hook.py
Labels: micro decision, ready to merge

#537 Remove old legacy code about letsencrypt_ynh
  locales/en.json
  src/yunohost/certificate.py
Labels: micro decision, ready to merge

#511 Add su directive as option for logroate
  data/helpers.d/backend
Labels: helper

#538 Add script to automatically generate helpers documentation
  doc/generate_helper_doc.py
  doc/helper_doc_template.html
Labels: opinion needed, small decision

#536 [enh] Don't backp user home with .nobackup file
  data/hooks/backup/17-data_home
Labels: opinion needed, small decision

#523 Add many print helpers
  data/helpers.d/print
Labels: helper

#541 [fix] Error due to unwanted backslash !
  data/hooks/backup/17-data_home
Labels: micro decision, ready to merge

#540 [enh] Don't send email if no certificate need to be renewed
  src/yunohost/certificate.py
Labels: micro decision, ready to merge

#520 Add the internal helper ynh_handle_getopts_args
  data/helpers.d/getopts
Labels: helper, opinion needed, ready to merge, small decision

#543 [enh] Display only used fingerprint in bootprompt
  bin/yunoprompt
Labels: opinion needed, small decision
