Repository YunoHost/yunohost, pull requests merged in 2018-02, with the labels that each got.

#399 Fix security of nginx headers .
  data/templates/nginx/plain/yunohost_admin.conf
  data/templates/nginx/server.tpl.conf
Labels: important, opinion needed, small decision, work needed

#403 Add commands to allow/disallow a yunohost user to connect in ssh
  data/actionsmap/yunohost.yml
  src/yunohost/user.py
Labels: opinion needed, ready to merge, small decision

#404 [enh] add commands to manage authorized-keys of users
  data/actionsmap/yunohost.yml
  src/yunohost/ssh.py
  src/yunohost/user.py
Labels: opinion needed, small decision
