Repository YunoHost/yunohost, pull requests merged in 2018-06, with the labels that each got.

#487 [enh] Verbose by default
  bin/yunohost
  src/yunohost/app.py
  src/yunohost/backup.py
  src/yunohost/certificate.py
  src/yunohost/data_migrations/0002_migrate_to_tsig_sha256.py
  src/yunohost/data_migrations/0003_migrate_to_stretch.py
  src/yunohost/domain.py
  src/yunohost/dyndns.py
  src/yunohost/firewall.py
  src/yunohost/hook.py
  src/yunohost/service.py
  src/yunohost/tools.py
Labels: medium decision, ready to merge

#491 Remove archivemount stuff
  debian/control
  src/yunohost/backup.py
  src/yunohost/tests/test_backuprestore.py
Labels: opinion needed, small decision

#489 [fix] Redirect corectly php5 to php7 file during restore
  locales/en.json
  src/yunohost/backup.py
Labels: important, opinion needed, small decision

#490 Fix counter-intuitive backup API
  data/actionsmap/yunohost.yml
  src/yunohost/backup.py
Labels: opinion needed, small decision

#488 [enh] POC to allow applications to ship configurations panels for the software they bundle
  data/actionsmap/yunohost.yml
  locales/en.json
  src/yunohost/app.py
  src/yunohost/hook.py
Labels: opinion needed, small decision

#496 [fix] Mail permission issue after restore
  data/hooks/restore/23-data_mail
Labels: micro decision, ready to merge

#486 [enh] POC for app actions
  data/actionsmap/yunohost.yml
  src/yunohost/app.py
  src/yunohost/hook.py
Labels: small decision

#497 [fix] fix recursive super slow import in certificate.py
  src/yunohost/certificate.py
Labels: important, ready to merge, small decision

#499 [fix] Mark dns-root-data as conflicting with ynh
  debian/changelog
  debian/control
Labels: micro decision

#500 [fix] Conflict with a specific version of dns-root-data
  debian/changelog
  debian/control
Labels: micro decision

#502 [fix] timeout on get_public_ip otherwish dyndns update is stucked
  src/yunohost/utils/network.py
Labels: important, micro decision, ready to merge

#498 [ux] display human understandable choice for boolean type on installation
  src/yunohost/app.py
Labels: ready to merge, small decision
