Repository YunoHost/yunohost, pull requests merged in 2018-08, with the labels that each got.

#509 [mod] propagate the no_checks logic to acme-tiny code
  src/yunohost/certificate.py
  src/yunohost/vendor/acme_tiny/acme_tiny.py
Labels: ready to merge, small decision

#513 More agressive deprecation messages for app checkurl and initdb
  locales/en.json
  src/yunohost/app.py
Labels: small decision

#512 Better error path conflict
  locales/en.json
  src/yunohost/app.py
  src/yunohost/domain.py
Labels: opinion needed, ready to merge, small decision

#383 [enh] Add ynh_info helper for app scripts
  data/helpers.d/print
  src/yunohost/app.py
  src/yunohost/hook.py
Labels: helper, opinion needed, small decision

#515 Set equiv as base dependance
  data/helpers.d/package
  debian/control
Labels: micro decision, ready to merge

#514 [enh] Add fake-hwclock
  debian/control
Labels: micro decision, ready to merge

#532 [enh] add jq as a dependancy
  debian/control
Labels: ready to merge, small decision
