Repository YunoHost/yunohost, pull requests merged in 2018-07, with the labels that each got.

#504 Fix nodejs removal in ynh_remove_nodejs
  data/helpers.d/nodejs
Labels: opinion needed, ready to merge, small decision

#506 [enh] list available users on app installation user argument
  locales/en.json
  src/yunohost/app.py
Labels: ready to merge, small decision

#510 [enh] after postinstall tell admin to had its first user
  locales/en.json
  src/yunohost/tools.py
Labels: micro decision, ready to merge

#495 [enh] Add MUA autoconfig.
  data/hooks/conf_regen/15-nginx
  data/templates/nginx/autoconfig.tpl.xml
  data/templates/nginx/server.tpl.conf
  src/yunohost/app.py
Labels: opinion needed, small decision
