Repository YunoHost/yunohost, pull requests merged in 2018-10, with the labels that each got.

#545 [fix] Silent output/warning but display errors
  data/helpers.d/utils
Labels: helper, opinion needed, small decision

#524 Add ynh_delete_file_checksum
  data/helpers.d/filesystem
Labels: helper

#559 Update Metronome configuration file to v3.11 standard
  data/templates/metronome/metronome.cfg.lua
Labels: opinion needed, small decision

#557 [fix] Use random serial number for CA
  data/templates/ssl/openssl.cnf
  src/yunohost/tools.py
Labels: opinion needed, small decision

#533 OCSP Stapling
  data/hooks/conf_regen/15-nginx
  data/templates/nginx/server.tpl.conf
Labels: opinion needed, ready to merge, small decision

#528 [enh] integrate CAA DNS entry into "yunohost domain dns-conf"
  src/yunohost/domain.py
  src/yunohost/dyndns.py
Labels: opinion needed, ready to merge, small decision

#519 [fix] 'dyndns update' should check the upstream dns record
  src/yunohost/dyndns.py
Labels: important, ready to merge, small decision

#553 [fix] Improve the message w.a. when admins tries to create users with a reserved Email Address (Issue 1216)
  locales/en.json
  src/yunohost/user.py
Labels: opinion needed, ready to merge, small decision
