Repository YunoHost/yunohost, pull requests merged in 2018-03, with the labels that each got.

#438 [fix] [critical] Fail2ban conf/filter was not matching failed login attempts...
  data/templates/fail2ban/jail.conf
  data/templates/fail2ban/yunohost.conf
Labels: important, opinion needed, small decision

#428 [Fix] Stronger match for acme-challenge nginx location
  src/yunohost/certificate.py
Labels: opinion needed, small decision

#440 Misc fixes in the helpers to clean the autodoc
  data/helpers.d/backend
  data/helpers.d/filesystem
  data/helpers.d/ip
  data/helpers.d/mysql
  data/helpers.d/package
  data/helpers.d/print
  data/helpers.d/system
Labels: opinion needed, small decision

#398 [enh] Tranfer backup_core_only to BACKUP_CORE_ONLY
  data/helpers.d/filesystem
  data/helpers.d/utils
Labels: helper

#384 Solve issue with ynh_restore_file
  data/helpers.d/filesystem
Labels: helper, opinion needed

#443 Add wget as dependency
  debian/control
Labels: micro decision, ready to merge

#441 Add nodejs helpers
  data/helpers.d/nodejs
Labels: helper
