Repository YunoHost/yunohost, pull requests merged in 2018-11, with the labels that each got.

#196 [enh] Automatically check for weak password
  data/actionsmap/yunohost.yml
  data/other/password/100000-most-used.txt.gz
  debian/install
  locales/en.json
  src/yunohost/app.py
  src/yunohost/settings.py
  src/yunohost/tools.py
  src/yunohost/user.py
  src/yunohost/utils/password.py
Labels: important, medium decision, opinion needed, ready to merge

#527 Synchronize root and admin password
  data/actionsmap/yunohost.yml
  locales/en.json
  src/yunohost/data_migrations/0006_sync_admin_and_root_passwords.py
  src/yunohost/tools.py
Labels: important, opinion needed, ready to merge, small decision

#566 [fix] php conf files not properly removed when an app is uninstalled
  data/helpers.d/backend
Labels: important, opinion needed, small decision

#569 [enh] Use more blocks for dd in ynh_string_random
  data/helpers.d/string
Labels: helper

#571 [enh] Wait for dpkg lock to be free
  data/helpers.d/package
  debian/control
Labels: helper

#577 [fix] Unknown variable password in user_update
  src/yunohost/user.py
Labels: micro decision

#575 Fix app_addaccess behaviour when 'allowed_users' is initially empty
  src/yunohost/app.py
Labels: micro decision, opinion needed

#558 Do not fail on missing fail2ban config during the backup
  data/helpers.d/filesystem
Labels: helper, opinion needed, small decision

#579 Update ECDH curves recommended by Mozilla, now that we are on stretch
  data/templates/nginx/server.tpl.conf
Labels: opinion needed
