Repository YunoHost/yunohost, pull requests merged in 2019-03, with the labels that each got.

#639 [enh] Add IPv6 nameserver to resolv.dnsmasq.conf from diyisp.org
  data/templates/dnsmasq/plain/resolv.dnsmasq.conf
Labels: merging soon™, reviews needed, small decision

#662 [fix] Optimize dyndns requests
  src/yunohost/dyndns.py
Labels: merging soon™, small decision, tests needed

#669 [enh] allow 'display_text' ~fake~ argument in manifest.json
  src/yunohost/app.py
Labels: small decision

#526 [enh] Allow hooks to return data
  locales/en.json
  src/yunohost/app.py
  src/yunohost/backup.py
  src/yunohost/hook.py
  src/yunohost/service.py
Labels: merging soon™, reviews needed, small decision

#633 [enh] Add ynh_systemd_action helper
  data/helpers.d/backend
  data/helpers.d/system
Labels: app helpers, merging soon™, reviews needed, small decision

#663 [enh] Optimize app setting helpers
  data/helpers.d/setting
Labels: app helpers, merging soon™, reviews needed, small decision

#657 [enh] Update psql helper
  data/helpers.d/psql
Labels: app helpers, merging soon™, reviews needed, small decision

#676 [fix] ynh_app_setting_get and ynh_app_setting_delete don't have a fou…
  data/helpers.d/setting
Labels: app helpers

#673 Fix backup tests
  src/yunohost/backup.py
  src/yunohost/tests/test_backuprestore.py
Labels: micro decision, small decision

#675 [fix] Disable gzip entirely
  data/templates/nginx/plain/global.conf
Labels: reviews needed, small decision

#672 [fix] Backup fails because output directory not empty
  src/yunohost/backup.py
  src/yunohost/tests/test_backuprestore.py
Labels: reviews needed, small decision

#671 [fix] Reject app password if they contains { or }
  locales/en.json
  src/yunohost/app.py
Labels: reviews needed, small decision

#680 [fix] Delete properly group as well as user
  data/helpers.d/user
Labels: app helpers, merging soon™

#681 [enh] reload-or-restart instead of reload
  data/helpers.d/system
Labels: app helpers, merging soon™

#664 Add min version for all helpers
  data/helpers.d/backend
  data/helpers.d/debug
  data/helpers.d/filesystem
  data/helpers.d/getopts
  data/helpers.d/ip
  data/helpers.d/mysql
  data/helpers.d/network
  data/helpers.d/nodejs
  data/helpers.d/package
  data/helpers.d/print
  data/helpers.d/psql
  data/helpers.d/setting
  data/helpers.d/string
  data/helpers.d/system
  data/helpers.d/user
  data/helpers.d/utils
Labels: app helpers

#517 [enh] Hooks to allow apps to extend the recommended DNS configuration
  src/yunohost/domain.py
Labels: merging soon™, reviews needed, small decision

#640 [enh] use setting security_ciphers_compatibility to define security configu…
  data/hooks/conf_regen/03-ssh
  data/hooks/conf_regen/15-nginx
  data/templates/nginx/plain/yunohost_admin.conf
  data/templates/nginx/server.tpl.conf
  data/templates/ssh/sshd_config
  locales/en.json
  src/yunohost/settings.py
Labels: merging soon™, reviews needed, small decision

#674 [enh] Support php versions in ynh_add_fpm_config
  data/helpers.d/backend
Labels: app helpers, merging soon™
