Repository YunoHost/yunohost, pull requests merged in 2019-08, with the labels that each got.

#765 [mod] BREAKING (but should be fine) apps without path aren't considering using the domain anymore
  src/yunohost/app.py
Labels: small decision

#755 [enh] Add OpenLDAP TLS support
  data/hooks/conf_regen/06-slapd
  data/templates/slapd/slapd.conf
Labels: merging soon™

#766 [mod] remove silent exception in toos_update
  locales/en.json
  src/yunohost/tools.py
Labels: small decision

#752 [fix] Fix values starting by - in getopts
  data/helpers.d/getopts
Labels: app helpers

#748 Manifest in toml
  src/yunohost/app.py
Labels: merging soon™, small decision

#767 [ux] better error message for not installed app
  locales/en.json
  src/yunohost/app.py
Labels: merging soon™, small decision

#764 [enh] integrate actions/config-panel into operation_logs
  src/yunohost/app.py
Labels: small decision

#772 [fix] dpkg-origins
  data/other/dpkg-origins/yunohost
  debian/install
Labels: micro decision

#781 Small cleaning and update of the README.md
  README.md
Labels: micro decision

#753 [enh] Upgrade n version (also for compatibility with arm64)
  data/helpers.d/nodejs
Labels: app helpers

#762 [enh] PostgreSQL password security
  data/helpers.d/postgresql
  locales/en.json
  src/yunohost/data_migrations/0012_postgresql_password_to_md5_authentication.py
Labels: merging soon™

#743 Fix wrong usage of ynh_mysql_user_exists
  data/helpers.d/mysql
Labels: app helpers, merging soon™

#747 Python hooks reloaded
  src/yunohost/hook.py
Labels: merging soon™, reviews needed
