Repository YunoHost/yunohost, pull requests merged in 2019-09, with the labels that each got.

#786 "yunohost dyndns update" "--force" and "--dry-run"
  data/actionsmap/yunohost.yml
  src/yunohost/dyndns.py
Labels: merging soon™, small decision

#790 [enh] Rename permission http api route in plural
  data/actionsmap/yunohost.yml
Labels: micro decision

#769 Stop on failed app upgrade
  locales/en.json
  src/yunohost/app.py
Labels: important, merging soon™, small decision

#785 [enh] Iteration on sanity / anomaly checks for app operations
  locales/en.json
  src/yunohost/app.py
Labels: merging soon™, reviews needed

#779 [enh] Add unit/functional tests for apps
  src/yunohost/app.py
  src/yunohost/tests/conftest.py
  src/yunohost/tests/test_apps.py
Labels: merging soon™, reviews needed, small decision

#800 Language reworked
  README.md
Labels: micro decision

#792 Check that exist before the calculate the checksum
  data/helpers.d/backup
Labels: app helpers, merging soon™

#793 [fix] Stale / undefined i18n strings
  locales/en.json
  src/yunohost/app.py
  src/yunohost/tools.py
  tests/_test_m18nkeys.py
Labels: merging soon™

#802 change maxretry of fail2ban from 6 to 10
  data/templates/fail2ban/yunohost-jails.conf
Labels: merging soon™, micro decision
