Repository YunoHost/yunohost, pull requests merged in 2019-05, with the labels that each got.

#716 Add a --with-details option for log list
  data/actionsmap/yunohost.yml
  src/yunohost/log.py
Labels: merging soon™

#692 [enh] Rework tools_update and tools_upgrade
  data/actionsmap/yunohost.yml
  locales/en.json
  src/yunohost/app.py
  src/yunohost/log.py
  src/yunohost/tools.py
  src/yunohost/utils/packages.py
Labels: medium decision, merging soon™, reviews needed

#696 [enh] Propose a setting to remove support for TLSv1 and TLSv1.1 in Postfix
  data/hooks/conf_regen/19-postfix
  data/templates/postfix/main.cf
  locales/en.json
  src/yunohost/settings.py
Labels: merging soon™, reviews needed

#722 Disable VRFY command in Postfix command
  data/templates/postfix/main.cf
Labels: merging soon™

#691 [enh] Avoid to send simultaneously too much emails
  data/templates/postfix/main.cf
Labels: merging soon™, reviews needed, small decision

#720 Add helpers for sso config
  data/helpers.d/setting
Labels: app helpers, merging soon™

#687 Dump ynh log if an app script fails
  data/helpers.d/utils
  src/yunohost/hook.py
Labels: app helpers, merging soon™, reviews needed

#721 [enh] Simplify the whole LDAP interface thing
  data/actionsmap/yunohost.yml
  data/templates/slapd/slapd.conf
  src/yunohost/app.py
  src/yunohost/backup.py
  src/yunohost/certificate.py
  src/yunohost/domain.py
  src/yunohost/log.py
  src/yunohost/ssh.py
  src/yunohost/tests/test_appurl.py
  src/yunohost/tests/test_backuprestore.py
  src/yunohost/tests/test_changeurl.py
  src/yunohost/tools.py
  src/yunohost/user.py
  src/yunohost/utils/ldap.py
Labels: merging soon™, reviews needed

#728 Allow to display logs when postinstall fails
  bin/yunohost
Labels: merging soon™

#729 Add indexes for fields listed by slapd in the logs
  data/templates/slapd/slapd.conf
Labels: merging soon™
