Repository YunoHost/yunohost, pull requests merged in 2019-01, with the labels that each got.

#610 [fix] propagate --no-checks cert-install option to renew crontab
  src/yunohost/certificate.py
Labels: opinion needed, small decision, test needed

#614 Enforce --force-confold during apt upgrade
  src/yunohost/tools.py
Labels: opinion needed, ready to merge, small decision

#608 [fix] Fix the way change_url updates the domain/path
  data/actionsmap/yunohost.yml
  locales/en.json
  src/yunohost/app.py
  src/yunohost/domain.py
  src/yunohost/tests/test_changeurl.py
Labels: opinion needed, ready to merge, small decision

#613 [fix] Set owner of archives folder to 'admin'
  src/yunohost/backup.py
  src/yunohost/data_migrations/0008_ssh_conf_managed_by_yunohost_step2.py
Labels: opinion needed, ready to merge, small decision

#615 [enh] Change git clone for gitlab working with branch
  src/yunohost/app.py
Labels: opinion needed, ready to merge, small decision

#616 [fix] `_run_service_command` not properly returning False if command fails
  src/yunohost/service.py
Labels: micro decision

#625 [enh] Keep it fucking clear...
  data/helpers.d/package
Labels: helper, micro decision

#626 [fix] app conflicting with itself during change_url
  src/yunohost/app.py
  src/yunohost/domain.py
Labels: small decision, test needed

#620 Update spectre meltdown checker
  src/yunohost/vendor/spectre-meltdown-checker/Dockerfile
  src/yunohost/vendor/spectre-meltdown-checker/README.md
  src/yunohost/vendor/spectre-meltdown-checker/docker-compose.yml
  src/yunohost/vendor/spectre-meltdown-checker/spectre-meltdown-checker.sh
Labels: opinion needed, small decision

#455 [enh] Control the login shell when creating users in ynh_system_user_create
  data/helpers.d/user
Labels: helper, opinion needed, small decision

#628 [fix] Update ynh_handle_getopts_args
  data/helpers.d/getopts
Labels: helper

#629 [fix] Fix home_dir unset in ynh_system_user_create
  data/helpers.d/user
Labels: helper, micro decision, ready to merge

#632 [fix] Do not log migration to stretch in /tmp/. Issue #1280
  src/yunohost/data_migrations/0003_migrate_to_stretch.py
Labels: small decision, test needed
