Repository YunoHost/yunohost, pull requests merged in 2019-06, with the labels that each got.

#730 [fix] current version in app_info
  src/yunohost/app.py
Labels: merging soon™

#724 Remove unecessary log messages
  data/helpers.d/mysql
  data/helpers.d/postgresql
  data/helpers.d/systemd
  data/helpers.d/user
Labels: app helpers, merging soon™

#726 [fix] Stupid issue with files inside tar : foo is not the same as ./foo
  src/yunohost/backup.py
Labels: merging soon™

#732 [enh] support config_panel in TOML format
  debian/control
  src/yunohost/app.py
Labels: small decision

#741 Use set +x / -x to hide the whole ynh_script_progression computation
  data/helpers.d/logging
Labels: app helpers, merging soon™
