Repository YunoHost/yunohost, pull requests merged in 2019-07, with the labels that each got.

#745 [fix] Missing internetcube list
  src/yunohost/data_migrations/0010_migrate_to_apps_json.py
Labels: micro decision

#682 [enh] Script to generate manpages (issues#284)
  debian/install
  debian/rules
  doc/generate_manpages.py
  doc/manpage.template
Labels: merging soon™, small decision

#744 [enh] allows actions.toml
  src/yunohost/app.py
Labels: small decision

#585 Group permission
  data/actionsmap/yunohost.yml
  data/helpers.d/setting
  data/hooks/conf_regen/06-slapd
  data/other/ldap_scheme.yml
  data/templates/dovecot/dovecot-ldap.conf
  data/templates/metronome/domain.tpl.cfg.lua
  data/templates/postfix/plain/ldap-accounts.cf
  data/templates/postfix/plain/ldap-aliases.cf
  data/templates/slapd/slapd.conf
  data/templates/slapd/yunohost.schema
  locales/en.json
  src/yunohost/app.py
  src/yunohost/backup.py
  src/yunohost/data_migrations/0011_setup_group_permission.py
  src/yunohost/permission.py
  src/yunohost/tests/test_appurl.py
  src/yunohost/tests/test_backuprestore.py
  src/yunohost/tests/test_permission.py
  src/yunohost/tests/test_user-group.py
  src/yunohost/tools.py
  src/yunohost/user.py
Labels: big decision, depends on other PR, important, tests needed

#761 [mod] don't truncate 'yunohost log display' log by default
  src/yunohost/log.py
Labels: small decision

#749 [enh] Dpkg vendor set to YunoHost
  data/other/dpkg-origins
  debian/install
  debian/postinst
  debian/postrm
Labels: reviews needed, small decision
