Repository YunoHost/yunohost, pull requests merged in 2019-02, with the labels that each got.

#637 [fix] Remove old SMTP port (465) from Fail2ban jail.conf
  data/templates/fail2ban/jail.conf
Labels: micro decision

#630 [enh] Allow to dig deeper into an archive with ynh_setup_source
  data/helpers.d/utils
Labels: helper, micro decision, ready to merge

#636 [fix] Update DNS resolver list according to diyisp.org
  data/templates/dnsmasq/plain/resolv.dnsmasq.conf
Labels: opinion needed, small decision

#635 Warn the user that ynh_secure_remove should be used with only one arg…
  data/helpers.d/filesystem
Labels: helper, opinion needed, small decision

#561 Use getops
  data/helpers.d/backend
  data/helpers.d/filesystem
  data/helpers.d/getopts
  data/helpers.d/ip
  data/helpers.d/mysql
  data/helpers.d/network
  data/helpers.d/nodejs
  data/helpers.d/package
  data/helpers.d/print
  data/helpers.d/setting
  data/helpers.d/string
  data/helpers.d/system
  data/helpers.d/user
  data/helpers.d/utils
Labels: helper, opinion needed, small decision

#642 Fix #635 on ynh_secure_remove
  data/helpers.d/filesystem
Labels: helper, micro decision

#641 [fix] Admin password appearing in logs
  bin/yunohost-api
Labels: important, opinion needed, small decision

#634 Add ynh_script_progression
  data/helpers.d/print
Labels: helper

#646 [fix] Escape double quote before eval in getopts
  data/helpers.d/getopts
Labels: helper, micro decision, small decision

#649 Reload fail2ban instead of restart
  src/yunohost/firewall.py
Labels: small decision

#644 [fix] ynh_local_curl
  data/helpers.d/utils
Labels: helper, ready to merge, small decision

#651 [fix] Loading only one helper file leads to errors because missing getopts
  data/hooks/backup/05-conf_ldap
  data/hooks/backup/08-conf_ssh
  data/hooks/backup/11-conf_ynh_mysql
  data/hooks/backup/14-conf_ssowat
  data/hooks/backup/17-data_home
  data/hooks/backup/20-conf_ynh_firewall
  data/hooks/backup/21-conf_ynh_certs
  data/hooks/backup/23-data_mail
  data/hooks/backup/26-conf_xmpp
  data/hooks/backup/29-conf_nginx
  data/hooks/backup/32-conf_cron
  data/hooks/backup/40-conf_ynh_currenthost
  data/hooks/conf_regen/03-ssh
  data/hooks/conf_regen/15-nginx
  data/hooks/conf_regen/34-mysql
  data/hooks/conf_regen/43-dnsmasq
  data/hooks/restore/11-conf_ynh_mysql
Labels: micro decision, test needed

#521 Add ynh_check_app_version_changed
  data/helpers.d/system
Labels: helper, ready to merge

#364 [enh] Add fail2ban helpers
  data/helpers.d/backend
Labels: helper, ready to merge, small decision

#622 Improve protection against indexation from the robots.
  data/templates/nginx/plain/yunohost_admin.conf
Labels: opinion needed, ready to merge, small decision

#638 [enh] Check if dpkg is not broken when calling ynh_wait_dpkg_free
  data/helpers.d/package
Labels: helper, ready to merge

#647 Add app debugger helper
  data/helpers.d/debug
Labels: helper

#655 [enh] Ensure the tar file is closed during the backup
  locales/en.json
  src/yunohost/backup.py
Labels: micro decision, ready to merge

#291 [fix] Remove version from api
  bin/yunohost-api
Labels: opinion needed, small decision

#643 [fix] Get rid of annoying 'unable to initialize frontend' messages
  data/helpers.d/package
Labels: opinion needed, ready to merge, small decision

#658 Add apt-transport-https to dependencies
  debian/control
Labels: opinion needed, ready to merge, small decision

#656 Cache results from meltdown checker
  src/yunohost/tools.py
Labels: opinion needed, small decision

#648 [enh] Print diff of files when backup by ynh_backup_if_checksum_is_different
  data/helpers.d/filesystem
Labels: helper, opinion needed, ready to merge, small decision

#650 [enh] Improve / add some messages to improve UX
  locales/en.json
  src/yunohost/app.py
  src/yunohost/backup.py
Labels: micro decision, ready to merge, test needed

#652 [enh] Assert dpkg is not broken before app install
  locales/en.json
  src/yunohost/app.py
  src/yunohost/tools.py
  src/yunohost/utils/packages.py
Labels: opinion needed, small decision

#654 [enh] Be able to define hook to trigger when changing a setting
  src/yunohost/settings.py
Labels: opinion needed, small decision

#661 [enh] Don't add Strict-Transport-Security header in nginx conf if using a selfsigned cert
  data/templates/nginx/server.tpl.conf
Labels: opinion needed, ready to merge, small decision

#660 [enh] Add the arch argument to ynh_install_nodejs
  data/helpers.d/nodejs
Labels: opinion needed, ready to merge, small decision
