Repository YunoHost/yunohost, pull requests merged in 2019-04, with the labels that each got.

#689 [enh] Nginx conf tweaks for theme
  data/templates/nginx/plain/yunohost_panel.conf.inc
Labels: merging soon™, reviews needed, small decision

#685 Avoid having to shell-escape arguments in ynh_handle_getopts_args
  data/helpers.d/getopts
Labels: merging soon™, small decision

#670 [enh] Check that required services are up before running app install and upgrade
  locales/en.json
  src/yunohost/app.py
Labels: reviews needed, small decision

#697 [mod] use ask key for display_text instead and support i18n
  src/yunohost/app.py
Labels: reviews needed, small decision

#698 [fix] Fix the dbus interface to get info for services
  src/yunohost/service.py
Labels: merging soon™, reviews needed, small decision

#695 [fix] Rework tools update (only)
  locales/en.json
  src/yunohost/tools.py
Labels: reviews needed, small decision

#710 [fix] Fix extraction of weight value for ynh_script_progression
  data/helpers.d/print
Labels: app helpers

#653 [enh] Decouple the regen-conf mechanism from services
  data/actionsmap/yunohost.yml
  data/templates/yunohost/services.yml
  debian/postinst
  locales/en.json
  src/yunohost/backup.py
  src/yunohost/certificate.py
  src/yunohost/data_migrations/0003_migrate_to_stretch.py
  src/yunohost/data_migrations/0007_ssh_conf_managed_by_yunohost_step1.py
  src/yunohost/data_migrations/0008_ssh_conf_managed_by_yunohost_step2.py
  src/yunohost/data_migrations/0009_decouple_regenconf_from_services.py
  src/yunohost/domain.py
  src/yunohost/regenconf.py
  src/yunohost/service.py
  src/yunohost/tools.py
Labels: medium decision, reviews needed

#714 [fix] ynh_psql_remove_db fail
  data/helpers.d/psql
Labels: important, micro decision

#665 Use apps.json as default list
  src/yunohost/tools.py
Labels: merging soon™, reviews needed

#666 Migrate to apps.json
  locales/en.json
  src/yunohost/data_migrations/0010_migrate_to_apps_json.py
Labels: merging soon™, reviews needed

#694 [enh] Mark YunoHost as essential to avoid removing it inadvertenly
  debian/control
Labels: merging soon™, reviews needed, small decision

#715 [enh] Add the current work to the progression bar
  data/helpers.d/print
Labels: merging soon™

#713 Force disconnection of all clients connected to the database
  data/helpers.d/psql
Labels: merging soon™, reviews needed

#712 Use printers in helpers
  data/helpers.d/filesystem
  data/helpers.d/mysql
  data/helpers.d/nodejs
  data/helpers.d/package
  data/helpers.d/psql
  data/helpers.d/system
  data/helpers.d/user
  data/helpers.d/utils
Labels: app helpers, merging soon™

#711 Use ynh_systemd_action
  data/helpers.d/backend
  data/helpers.d/psql
Labels: app helpers, merging soon™

#709 [enh] Specify -a parameter on dovecot lda for Sieve
  data/templates/postfix/plain/master.cf
Labels: merging soon™, reviews needed

#706 [enh] Bind OpenLDAP socket on localhost
  data/templates/slapd/slapd.default
Labels: merging soon™

#704 [FIX] Hook backup warning message
  data/hooks/backup/32-conf_cron
Labels: merging soon™

#701 [enh] WebSocket proxying
  data/templates/nginx/server.tpl.conf
Labels: merging soon™

#699 Add size of apps in backup_info result
  src/yunohost/backup.py
Labels: merging soon™

#678 [enh] bash completion for yunohost cli
  data/actionsmap/yunohost_completion.py
  data/bash-completion.d/yunohost
  debian/rules
Labels: merging soon™, reviews needed, small decision
