Repository YunoHost/yunohost, pull requests merged in 2019-11, with the labels that each got.

#824 Remove app_debug, unused stuff / not really relevant
  data/actionsmap/yunohost.yml
  src/yunohost/app.py
Labels: merging soon™

#758 [fix] moulinette logs were never displayed #lol
  bin/yunohost
Labels: merging soon™, small decision

#821 Remove the whole monitoring / glances stuff
  data/actionsmap/yunohost.yml
  data/templates/glances/glances.default
  data/templates/yunohost/services.yml
  debian/control
  locales/en.json
  src/yunohost/monitor.py
Labels: merging soon™

#796 Maindomain ux feedback
  data/actionsmap/yunohost.yml
  locales/ar.json
  locales/ca.json
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/it.json
  locales/oc.json
  locales/pt.json
  src/yunohost/domain.py
  src/yunohost/tools.py
Labels: merging soon™, small decision

#805 Simplify madness code about checking requirements
  locales/en.json
  src/yunohost/app.py
  src/yunohost/utils/packages.py
Labels: merging soon™

#534 [enh] New diagnosis system
  data/actionsmap/yunohost.yml
  data/hooks/diagnosis/00-basesystem.py
  data/hooks/diagnosis/10-ip.py
  data/hooks/diagnosis/12-dnsrecords.py
  data/hooks/diagnosis/14-ports.py
  data/hooks/diagnosis/16-http.py
  data/hooks/diagnosis/18-mail.py
  data/hooks/diagnosis/30-services.py
  data/hooks/diagnosis/50-systemresources.py
  data/hooks/diagnosis/70-regenconf.py
  data/hooks/diagnosis/90-security.py
  data/templates/nginx/server.tpl.conf
  locales/en.json
  src/yunohost/app.py
  src/yunohost/diagnosis.py
  src/yunohost/regenconf.py
  src/yunohost/tools.py
Labels: medium decision, merging soon™, reviews needed

#778 [enh] Rebuild applist system and make it future proof
  data/actionsmap/yunohost.yml
  locales/en.json
  src/yunohost/app.py
  src/yunohost/data_migrations/0010_migrate_to_apps_json.py
  src/yunohost/data_migrations/0013_futureproof_apps_catalog_system.py
  src/yunohost/tests/test_appscatalog.py
  src/yunohost/tests/test_appslist.py
  src/yunohost/tools.py
Labels: medium decision, merging soon™, reviews needed

#780 [mod] Remove deprecated helpers while still supporting them through hacky patching
  data/actionsmap/yunohost.yml
  data/helpers.d/network
  locales/en.json
  src/yunohost/app.py
  src/yunohost/backup.py
  src/yunohost/tools.py
Labels: app helpers, merging soon™, reviews needed

#832 Improve app_upgrade error management
  locales/en.json
  src/yunohost/app.py
Labels: reviews needed, small decision

#833 Dump app debug extract from the core
  data/helpers.d/utils
  src/yunohost/app.py
  src/yunohost/backup.py
Labels: app helpers, reviews needed, small decision

#834 Get rid of app's status.json
  data/actionsmap/yunohost.yml
  locales/en.json
  src/yunohost/app.py
  src/yunohost/data_migrations/0014_remove_app_status_json.py
  src/yunohost/tools.py
Labels: merging soon™, reviews needed, small decision

#838 [enh] Improve service status checks (and service add CLI)
  data/actionsmap/yunohost.yml
  data/hooks/conf_regen/01-yunohost
  data/hooks/diagnosis/14-ports.py
  data/hooks/diagnosis/30-services.py
  data/hooks/diagnosis/70-regenconf.py
  data/templates/yunohost/services.yml
  locales/en.json
  src/yunohost/app.py
  src/yunohost/service.py
Labels: merging soon™, reviews needed

#791 Add pop3.enabled setting
  data/hooks/conf_regen/25-dovecot
  data/templates/dovecot/dovecot.conf
  locales/en.json
  src/yunohost/app.py
  src/yunohost/settings.py
  src/yunohost/tests/test_settings.py
Labels: merging soon™, small decision

#784 Propagate change on LDAP conf / authenticator
  src/yunohost/utils/ldap.py
Labels: depends on other PR
