Repository YunoHost/yunohost, pull requests merged in 2020-04, with the labels that each got.

#907 Fix ynh_find_port
  data/helpers.d/network
Labels: micro decision

#910 Drop ynh_add_skipped/(un)protected_uris helpers
  data/helpers.d/setting
Labels: app helpers, merging soon™

#918 [fix] config_appy return link
  src/yunohost/app.py
Labels: micro decision, reviews needed

#919 Dont diagnose all records for subdomains
  data/hooks/diagnosis/12-dnsrecords.py
  src/yunohost/domain.py
  src/yunohost/dyndns.py
Labels: merging soon™, micro decision

#857 [fix] prevent firefox to mix CA and server certificate
  src/yunohost/tools.py
Labels: merging soon™

#880 Pave the way to migration to php7.3 and following
  data/helpers.d/nginx
  data/helpers.d/php
  src/yunohost/app.py
Labels: app helpers

#881 New helpers for PHP and extra apt repo
  data/helpers.d/apt
  data/helpers.d/hardware
  data/helpers.d/php
Labels: app helpers, merging soon™

#915 Use a dedicated php service for each app
  data/helpers.d/php
Labels: app helpers, merging soon™

#928 More min_spare_servers for heavy apps
  data/helpers.d/php
Labels: app helpers, merging soon™

#925 [fix] custom_portal and custom_overlay redirect
  data/templates/nginx/plain/yunohost_panel.conf.inc
Labels: merging soon™

#929 Allow to overwrite pm.max_children
  data/helpers.d/php
Labels: app helpers, merging soon™

#921 [enh] Some mail checks
  data/hooks/diagnosis/24-mail.py
  data/other/dnsbl_list.yml
  debian/install
  locales/en.json
Labels: work needed

#948 Fix getopts with empty parameters
  data/helpers.d/getopts
Labels: merging soon™, micro decision

#949 Fix postfix ciphers
  data/templates/postfix/main.cf
Labels: important, small decision

#943 [fix] Add a new dig() helper to fix misc diagnosis issues that rely on dns queries
  data/hooks/diagnosis/12-dnsrecords.py
  data/hooks/diagnosis/24-mail.py
  src/yunohost/utils/network.py
Labels: small decision

#916 [enh] Setup all XMPP components for each "parent" domains
  data/actionsmap/yunohost.yml
  data/hooks/conf_regen/12-metronome
  data/templates/metronome/domain.tpl.cfg.lua
  data/templates/metronome/metronome.cfg.lua
  src/yunohost/certificate.py
  src/yunohost/domain.py
Labels: merging soon™

#957 use ynh_port_available in ynh_find_port
  data/helpers.d/network
Labels: app helpers

#813 [fix] Psql user should own the database
  data/helpers.d/postgresql
Labels: small decision, tests needed

#946 [fix] Be more robust against manually modified domain conf
  .gitlab-ci.yml
  data/hooks/conf_regen/15-nginx
  src/yunohost/domain.py
  src/yunohost/regenconf.py
  src/yunohost/tests/test_regenconf.py
Labels: small decision

#942 Wait for fail2ban to reload
  data/helpers.d/fail2ban
  data/helpers.d/systemd
Labels: app helpers

#947 Clean helpers
  data/helpers.d/apt
  data/helpers.d/backup
  data/helpers.d/fail2ban
  data/helpers.d/getopts
  data/helpers.d/hardware
  data/helpers.d/logging
  data/helpers.d/logrotate
  data/helpers.d/mysql
  data/helpers.d/network
  data/helpers.d/nginx
  data/helpers.d/nodejs
  data/helpers.d/php
  data/helpers.d/postgresql
  data/helpers.d/setting
  data/helpers.d/string
  data/helpers.d/systemd
  data/helpers.d/user
  data/helpers.d/utils
Labels: app helpers

#812 [enh] Add some advice about a strange locale problem with postgresql
  data/helpers.d/postgresql
Labels: micro decision

#944 [enh] Check domain expiration date
  data/hooks/diagnosis/12-dnsrecords.py
  debian/control
  locales/en.json
  tests/test_i18n_keys.py
Labels: merging soon™, small decision

#958 Misc optimizations to speed up regen-conf and other things
  data/hooks/conf_regen/12-metronome
  data/hooks/conf_regen/15-nginx
  data/hooks/conf_regen/19-postfix
  data/hooks/conf_regen/31-rspamd
  data/hooks/conf_regen/43-dnsmasq
  src/yunohost/regenconf.py
  src/yunohost/utils/network.py
Labels: merging soon™

#954 Fix helper patching + patch usage of old 'yunohost tools diagnosis'
  src/yunohost/app.py
Labels: merging soon™

#937 [enh] add dynamic variables to systemd helper
  data/helpers.d/systemd
Labels: app helpers, merging soon™

#964 [fix] Reverse DNS check
  data/hooks/diagnosis/24-mail.py
Labels: micro decision
