Repository YunoHost/yunohost, pull requests merged in 2020-09, with the labels that each got.

#1020 Backup to uncompressed tar by default
  locales/en.json
  src/yunohost/backup.py
  src/yunohost/settings.py
  src/yunohost/tests/test_backuprestore.py
  tests/test_i18n_keys.py
Labels: merging soon™

#864 Implement `upgrade_only_if_version_changes` in manifest
  data/actionsmap/yunohost.yml
  data/helpers.d/utils
  src/yunohost/app.py
Labels: merging soon™

#973 Add doc about is_big
  data/helpers.d/backup
Labels: app helpers

#962 [enh] c.f. issue 1365, asking a mail address during user creation is confusing ux, people try enter their existing mail addresses
  data/actionsmap/yunohost.yml
  locales/en.json
  src/yunohost/tests/test_user-group.py
  src/yunohost/user.py
Labels: merging soon™

#1013 WIP: Refactoring yunohost format arguments parsing
  locales/en.json
  src/yunohost/app.py
  src/yunohost/tests/test_apps_arguments_parsing.py
Labels: work needed

#773 [enh] Allow admin to specify an smtp relay
  data/hooks/conf_regen/19-postfix
  data/templates/postfix/main.cf
  locales/en.json
  src/yunohost/settings.py
Labels: small decision

#1049 [enh] Refactoring of package download process
  src/yunohost/app.py
Labels: small decision

#860 [enh] Sort alphabetically the domain list
  src/yunohost/domain.py
Labels: merging soon™, reviews needed, small decision

#818 Update the email regex so it accept the '+' sign.
  data/actionsmap/yunohost.yml
  locales/en.json
Labels: merging soon™, micro decision

#1022 Add default domain to API response
  src/yunohost/domain.py
Labels: work needed

#1055 Add ynh_add_config helper
  data/helpers.d/utils
Labels: app helpers, merging soon™

#1056 [enh] Add x509 fingerprint in /etc/issue
  bin/yunoprompt
Labels: small decision

#935 Remove legacy settings
  data/helpers.d/setting
  locales/en.json
  src/yunohost/app.py
  src/yunohost/backup.py
  src/yunohost/data_migrations/0019_extends_permissions_features_1.py
  src/yunohost/utils/legacy.py
Labels: work needed
