Repository YunoHost/yunohost, pull requests merged in 2020-03, with the labels that each got.

#890 [fix] Make sure the group permission update contains unique elements
  src/yunohost/permission.py
Labels: micro decision

#863 Fix unit test and improve test stability
  src/yunohost/settings.py
  src/yunohost/tests/test_apps.py
  src/yunohost/tests/test_appscatalog.py
  src/yunohost/tests/test_permission.py
Labels: depends on other PR

#894 Allow public apps with no sso tile
  locales/en.json
  src/yunohost/app.py
  src/yunohost/permission.py
  src/yunohost/tests/test_permission.py
Labels: merging soon™, micro decision

#895 Revoke before drop
  data/helpers.d/postgresql
Labels: merging soon™, micro decision

#902 Remove redirected_urls after postinstall
  src/yunohost/tools.py
  src/yunohost/user.py
Labels: merging soon™, micro decision

#831 XMPP http upload
  data/hooks/conf_regen/12-metronome
  data/hooks/conf_regen/15-nginx
  data/templates/metronome/metronome.cfg.lua
  data/templates/nginx/security.conf.inc
  data/templates/nginx/server.tpl.conf
  data/templates/ssl/openssl.cnf
  locales/en.json
  src/yunohost/certificate.py
  src/yunohost/domain.py
Labels: merging soon™, tests needed

#901 Unit tests / lint / cleaning for translation files
  locales/ar.json
  locales/bn_BD.json
  locales/br.json
  locales/ca.json
  locales/de.json
  locales/el.json
  locales/en.json
  locales/eo.json
  locales/es.json
  locales/eu.json
  locales/fr.json
  locales/hi.json
  locales/hu.json
  locales/it.json
  locales/nb_NO.json
  locales/ne.json
  locales/nl.json
  locales/oc.json
  locales/pl.json
  locales/pt.json
  locales/ru.json
  locales/sv.json
  locales/tr.json
  locales/zh_Hans.json
  src/yunohost/backup.py
  src/yunohost/data_migrations/0003_migrate_to_stretch.py
  src/yunohost/regenconf.py
  tests/_test_m18nkeys.py
  tests/remove_stale_translated_strings.py
  tests/test_i18n_keys.py
  tests/test_translation_format_consistency.py
Labels: merging soon™
