Repository YunoHost/yunohost, pull requests merged in 2021-06, with the labels that each got.

#1243 [enh] Accept attachment of 25MB instead of 21,8MB
  data/templates/postfix/main.cf
Labels: merging soon™, micro

#1164 [metronome/xmpp] deactivate stanza mention optimization / have quick notification in chat group
  data/templates/metronome/metronome.cfg.lua
Labels: xmpp

#1170 [metronome] activate module pubsub
  data/templates/metronome/metronome.cfg.lua
Labels: tests needed, xmpp

#1250 ci triggered only on file changed
  .gitlab/ci/test.gitlab-ci.yml
Labels: merging soon™, micro

#1249 ci triggered only for default branch or PR
  .gitlab-ci.yml
  .gitlab/ci/test.gitlab-ci.yml
Labels: merging soon™, micro

#1247 [enh] Remove LDN from resolver list
  data/templates/dnsmasq/plain/resolv.dnsmasq.conf
Labels: merging soon™, micro

#1251 Move some tests
  .gitlab-ci.yml
  .gitlab/ci/test.gitlab-ci.yml
  .gitlab/ci/translation.gitlab-ci.yml
Labels: merging soon™, micro
