Repository YunoHost/yunohost, pull requests merged in 2021-01, with the labels that each got.

#1120 [enh] display domain_path of app on app list
  src/yunohost/app.py
Labels: small decision

#1122 [mod] avoid calling app_list in user_permission_list
  src/yunohost/permission.py
Labels: micro decision

#1123 [fix] key name of app label wasn't the real label
  src/yunohost/app.py
Labels: micro decision

#1124 [mod] also display app label on remove_domain with apps
  locales/en.json
  src/yunohost/domain.py
Labels: micro decision

#1121 [doc] tell users how to get all permissions
  data/actionsmap/yunohost.yml
Labels: micro decision

#1069 Diagnosis: report usage of backports repository in apt's sources.list
  data/hooks/diagnosis/00-basesystem.py
  locales/en.json
Labels: merging soon™, micro decision

#1131 use read_yaml for json because lol
  src/yunohost/utils/legacy.py
Labels: #micro, merging soon™

#1117 New permissions helpers
  data/helpers.d/permission
  data/helpers.d/setting
Labels: #app helpers, #important, opinion needed, tests needed

#1109 firewall: force source port for UPnP.
  src/yunohost/firewall.py
Labels: #important, work needed

#1116 Python2 -> Python3
  .gitlab/ci/lint.gitlab-ci.yml
  .gitlab/ci/test.gitlab-ci.yml
  bin/yunohost
  bin/yunohost-api
  data/helpers.d/logging
  data/helpers.d/setting
  data/helpers.d/utils
  data/hooks/conf_regen/01-yunohost
  data/hooks/diagnosis/00-basesystem.py
  data/hooks/diagnosis/50-systemresources.py
  debian/control
  debian/rules
  doc/generate_helper_doc.py
  src/yunohost/app.py
  src/yunohost/backup.py
  src/yunohost/certificate.py
  src/yunohost/data_migrations/0019_extend_permissions_features.py
  src/yunohost/diagnosis.py
  src/yunohost/domain.py
  src/yunohost/dyndns.py
  src/yunohost/hook.py
  src/yunohost/log.py
  src/yunohost/permission.py
  src/yunohost/regenconf.py
  src/yunohost/service.py
  src/yunohost/settings.py
  src/yunohost/tests/test_apps.py
  src/yunohost/tests/test_apps_arguments_parsing.py
  src/yunohost/tests/test_appurl.py
  src/yunohost/tests/test_backuprestore.py
  src/yunohost/tests/test_changeurl.py
  src/yunohost/tests/test_permission.py
  src/yunohost/tests/test_regenconf.py
  src/yunohost/tests/test_service.py
  src/yunohost/tests/test_user-group.py
  src/yunohost/tools.py
  src/yunohost/user.py
  src/yunohost/utils/legacy.py
  src/yunohost/utils/packages.py
  src/yunohost/utils/password.py
  tox.ini
Labels: #big, merging soon™, tests needed

#1096 Less madness for hook exec
  src/yunohost/app.py
  src/yunohost/backup.py
  src/yunohost/hook.py
  src/yunohost/tests/conftest.py
  src/yunohost/user.py
Labels: merging soon™

#1090 [enh] Adding composer helper
  data/helpers.d/php
Labels: #app helpers, small work needed

#1077 Support more complex errors (be able to return additional data in a json structure)
  src/yunohost/app.py
  src/yunohost/utils/error.py
Labels: merging soon™, tests needed

#1070 Define a new "yunohost app search" command
  data/actionsmap/yunohost.yml
  src/yunohost/app.py
Labels: ready to merge

#1062 Refactor local CA management for more consistency and simpler postinstall
  data/hooks/conf_regen/02-ssl
  locales/en.json
  src/yunohost/domain.py
  src/yunohost/tools.py
Labels: merging soon™

#1063 Initialize folders during .deb install instead of regen conf
  data/hooks/conf_regen/01-yunohost
  src/yunohost/tools.py
Labels: merging soon™, tests needed

#1064 Move ldap initialization before the postinstall
  data/hooks/conf_regen/06-slapd
  data/hooks/conf_regen/09-nslcd
  data/hooks/conf_regen/46-nsswitch
  debian/postinst
  src/yunohost/__init__.py
  src/yunohost/tools.py
Labels: merging soon™, tests needed
