Repository YunoHost/yunohost, pull requests merged in 2021-04, with the labels that each got.

#1071 Add an option to disable the 'YunoHost' panel overlay in web apps
  data/hooks/conf_regen/15-nginx
  src/yunohost/settings.py
Labels: micro, tests needed

#1188 Sane default permissions for files added using ynh_add_config and ynh_setup_source
  data/helpers.d/utils
Labels: important

#1206 [fix] Remove passphrase keyword from logs
  src/yunohost/log.py
Labels: merging soon™, micro

#606 Add SFTP / SSH permissions
  data/actionsmap/yunohost.yml
  data/hooks/conf_regen/03-ssh
  data/hooks/diagnosis/70-regenconf.py
  data/other/ldap_scheme.yml
  data/templates/ssh/sshd_config
  locales/en.json
  src/yunohost/data_migrations/0019_extend_permissions_features.py
  src/yunohost/data_migrations/0020_ssh_sftp_permissions.py
  src/yunohost/permission.py
  src/yunohost/ssh.py
  src/yunohost/tests/test_apps_arguments_parsing.py
  src/yunohost/tools.py
  src/yunohost/user.py
Labels: small work needed
