Repository YunoHost/yunohost, pull requests merged in 2021-08, with the labels that each got.

#1275 [fix] Avoid to suspend server if we close lidswitch
  data/hooks/conf_regen/01-yunohost
Labels: tests needed

#1287 [fix] Avoid warning and use safeloader
  data/actionsmap/yunohost_completion.py
  data/helpers.d/setting
  data/hooks/conf_regen/01-yunohost
  doc/generate_manpages.py
  src/yunohost/app.py
  src/yunohost/firewall.py
  src/yunohost/regenconf.py
  src/yunohost/service.py
  tests/test_actionmap.py
  tests/test_i18n_keys.py
Labels: micro

#1112 Adding mDNS for .local domains
  bin/yunomdns
  data/hooks/conf_regen/37-avahi-daemon
  data/hooks/conf_regen/37-mdns
  data/hooks/diagnosis/12-dnsrecords.py
  data/hooks/diagnosis/21-web.py
  data/templates/avahi-daemon/avahi-daemon.conf
  data/templates/mdns/yunomdns.service
  data/templates/yunohost/services.yml
  debian/control
  debian/postinst
  locales/ar.json
  locales/ca.json
  locales/de.json
  locales/en.json
  locales/eo.json
  locales/es.json
  locales/fr.json
  locales/it.json
  locales/oc.json
  locales/zh_Hans.json
  src/yunohost/domain.py
Labels: important
