Repository YunoHost/yunohost, pull requests merged in 2021-02, with the labels that each got.

#1125 Add '--remove-apps' (and '--force') options to "yunohost domain remove"
  data/actionsmap/yunohost.yml
  locales/en.json
  src/yunohost/domain.py
Labels: tests needed

#1166 [fix] Avoid admin part of apps to be reachable from visitors
  src/yunohost/utils/legacy.py
Labels: important, merging soon™

#1129 Add multimedia helpers and hooks
  data/helpers.d/multimedia
  data/hooks/post_user_create/ynh_multimedia
  data/hooks/post_user_delete/ynh_multimedia
  debian/control
Labels: app helpers, tests needed

#1119 Simpler and more consistent logging initialization
  src/yunohost/__init__.py
  src/yunohost/diagnosis.py
  src/yunohost/service.py
Labels: work needed
