Repository YunoHost/yunohost, pull requests merged in 2022-08, with the labels that each got.

#1476 [fix] Be able to redo postinstall after 128+ chars password
  src/tools.py
  src/user.py
  src/utils/password.py
Labels: micro

#1478 App Config Panel : Don't restrict choices if there's no choices specified
  src/utils/config.py
Labels: micro, merging soon™

#1479 Saving app's venv in a requirements file, in order to regenerate it
  locales/en.json
  src/yunohost/data_migrations/0021_migrate_to_bullseye.py
Labels: tests needed

#1489 [fix] -f and --force are not thje same with yunohos app upgrade
  locales/en.json
Labels: micro
