Repository YunoHost/yunohost, pull requests merged in 2025-02, with the labels that each got.

#1917 app/permissions: Move permissions data out of LDAP, introduce a new 'app core' config panel allowing to change the app logo, label, etc.
  conf/slapd/config.ldif
  conf/slapd/db_init.ldif
  conf/slapd/permission.ldif
  helpers/helpers.v1.d/permission
  hooks/backup/20-conf_ynh_settings
  hooks/conf_regen/06-slapd
  hooks/restore/20-conf_ynh_settings
  locales/en.json
  maintenance/missing_i18n_keys.py
  share/actionsmap.yml
  share/config_app.toml
  src/app.py
  src/backup.py
  src/migrations/0028_delete_legacy_xmpp_permission.py
  src/migrations/0033_rework_permission_infos.py
  src/permission.py
  src/portal.py
  src/regenconf.py
  src/settings.py
  src/tests/test_app_resources.py
  src/tests/test_apps.py
  src/tests/test_permission.py
  src/tools.py
  src/user.py
  src/utils/configpanel.py
  src/utils/form.py
  src/utils/ldap.py
  src/utils/resources.py
Labels: work needed, 🚧 refactoring

#2041 [enh] Allow to login with a mail
  src/authenticators/ldap_ynhuser.py
Labels: micro, merging soon™

#1975 Improve LDAP performances when updating records, especially when many user entries exists
  conf/slapd/permission.ldif
  locales/en.json
  src/app.py
  src/portal.py
  src/settings.py
  src/user.py
  src/utils/ldap.py
Labels: important
